# Site settings
course_name: Data Mining & Machine Learning on Graphs
course_description: "Graph-structured data is ubiquitous among the world, e.g., social networks like Facebook, e-commerce platforms like Amazon, infrastructures like transportation graph, and chemical graphs like molecules. This course explores the graph analysis and basic machine learning methods for graph-related applications. Topics include: 1) Graph Foundations (basic graph properties and analysis techniques, e.g., centrality and statistical graph models); 2) Computational Methods for Graph-based Tasks (conventional and machine learning methods for link prediction/node classification/graph classification); 3) Real-world Applications (Recommender Systems; Social Anomaly Detection; Drug Discover; Knowledge Graph). Students will complete assigned homework, midterm exam and a team-based course project."
course_semester: "Fall-2024"

baseurl: "/fall-2024" # the subpath of your site, e.g. /blog/
url: "http://ML-Graph.github.io/" # the base hostname & protocol for your site

schoolname: "Department of Computer Science, University of Oregon"
schoolurl: "https://scds.uoregon.edu/cs"
twitter_username: username 

address: |
    University of Oregon
    Department of Computer Science
    Eugene, Oregon

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
